spring:
  application:
    name: poc

  ai:
    azure:
      openai:
        endpoint: https://api-b3gpt.b3.com.br/internal-api/b3gpt-llms/v1
        api-key: ${UNICAT-AZURE-OPENAI-API-KEY:}
        chat:
          options:
            deployment-name: gpt4o-mini
            temperature: 0.3
            max-tokens: 4096
